### ISSUE TITLE
Convert to Django project

### ISSUE THREAD

**Issue by harutmarg** [Hayk2508/web-scrapping#15]
## Motivation
Let's say users (clients) will want to get lists of parsed objects (f.e, links to media, or some text) via HTTP requests. Our project can serve as an API for clients to provide parsing logic (we can use `Django` for that).

## TODO
- rewrite the code in a way, so it live in a new Django project.
- `parsers` should be a separate app inside the project
- `main.py` script should live as a Django management command (https://docs.djangoproject.com/en/5.0/howto/custom-management-commands/). This will be only for us in case we want to download some data to local directories (or to server)
- create a **GET** endpoint with following params: `url`, `parse-type`. 
   The endpoint should return list of parsed objects in the following **JSON** schema: 
   `[{"obj-type": "image", "data": {"url": "someurl"}}]`
   `"data"` itself can have arbitrary schema. For now let's have `"url"` for media data, and `"text"` for tags

**Comment by Hayk2508** [comment]
Do i need to create a new django project in a separate folder and then include my code there,or i can create a new  django project directly in my folder that contains my whole code?

**Comment by Hayk2508** [comment]
It appears that i can create a new django project directly in my existing project,so i will do in this way
