### ISSUE TITLE
Add DB models and CRUD

### ISSUE THREAD

**Issue by harutmarg** [Hayk2508/web-scrapping#26]
## Motivation
 We want to save all objects during parsing to database, in order to save a history of outputs of our parsers. Also, the data can be used in CRUD operations for some frontend apps
 ## TODO
 - Add Django models that will represent parsed objects
 - Add logic to `parse` method for saving objects to database during parsing
 - Add CRUD API for those models
 - Add DB connection to local PostgreSQL instance (you can download `pgadmin4` for local debugging)

**Comment by Hayk2508** [comment]
I want to create model named 'MediaContent' and in this model will have these fields:   
    url = models.URLField() - this is url of the website
    parsed_urls = models.JSONField(default=list) - this represents parsed_urls of this website
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
Is this correct?

**Comment by Hayk2508** [comment]
Is this correct relation?
Url->Parser->ParsedObject
So at the end i should represent ParsedObject?
