### ISSUE TITLE
Add one option to select what to parse

### ISSUE THREAD

**Issue by harutmarg** [Hayk2508/web-scrapping#6]
Motivation:
 Currently in the script we have two arguments, which specify what to parse. 
Quite often (for example, in APIs), clients have to specify the types in one field of the payload (like parse_type), and the backend, based on the specified type, uses the corresponding instance of processor class (f.e ImageParser)

TODO: 
 Change two arguments in the script to one argument (parse_type). Based on the provided input, use the corresponding parser class. Think about scalability and what will happen, if we add more parsers in the future

**Comment by Hayk2508** [comment]
If i understand it well, then the user input should be like this: 
python .\main.py -url https://preply.com/en/tutor-signup -d C:\Users\User\Desktop\WebScrapping\Images -pt image

**Comment by Hayk2508** [comment]
I think if we will have more parser classes,it will be good to use the concept of polymorphism,but in our case,i think i cant realize it because each parser besides the common arguments(url,directory) also have specific arguments (f.e limit)
