### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by harutmarg** [Hayk2508/web-scrapping#9]
- Add unit tests for `parse`, `download`, `fetch` methods.

Use `unittest` module from Python's standard library (https://docs.python.org/3/library/unittest.html)

**Comment by Hayk2508** [comment]
If fetch  method is common for parsers,do i need to test fetch for every parser?

**Comment by Hayk2508** [comment]
> > If fetch method is common for parsers,do i need to test fetch for every parser?
> 
> 
> 
> if it is only one method implemented, how are you going to test for every parser? :D
Yes,you are right,since now I have not known,that I can create an instance of Asbtract class with tricks :).

**Comment by Hayk2508** [comment]
Now i can create an instance of MediaParser,and with that test fetch method
